**Analyse exploratoire**

Vous avez rejoint une nouvelle équipe dans le secteur de la banque de détail, qui connaît actuellement des taux de défaut plus élevés que prévu sur les prêts personnels. Les prêts personnels sont une source de revenus importante pour les banques, mais ils comportent le risque inhérent que les emprunteurs puissent faire défaut. Un défaut de paiement se produit lorsqu'un emprunteur cesse de faire les paiements requis sur une dette.

Objectif :
L'équipe de risque analyse le portefeuille de prêts existants pour prévoir les défauts potentiels futurs et estimer la perte attendue. L'objectif principal est de construire un modèle prédictif qui estime la probabilité de défaut pour chaque client en fonction de ses caractéristiques. Des prédictions précises permettront à la banque d'allouer suffisamment de capital pour couvrir les pertes potentielles, maintenant ainsi la stabilité financière.

1. Comprendre le contexte métier
Avant tout code :

Quelle est la question à laquelle tu veux répondre ?
Quelle est l'unité d'observation (une ligne = quoi ?) ?
Quelles variables sont cibles vs explicatives ?

In [6]:
import pandas as pd

df = pd.read_csv("/Users/ivanwinograd/IdeaProjects/Personnel/MLOps/Projet-MLops/Data/Loan_Data.csv")

df.shape          # dimensions
df.head()         # premières lignes
df.dtypes         # types de colonnes
df.info()         # vue d'ensemble + valeurs nulles
df.describe()     # statistiques descriptives

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               10000 non-null  int64
 1   credit_lines_outstanding  10000 non-null  int64
 2   loan_amt_outstanding      10000 non-null  float64
 3   total_debt_outstanding    10000 non-null  float64
 4   income                    10000 non-null  float64
 5   years_employed            10000 non-null  int64
 6   fico_score                10000 non-null  int64
 7   default                   10000 non-null  int64
dtypes: float64(3), int64(5)
memory usage: 625.1 KB

,customer_id,credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score,default
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.974577e+06,1.461200,4159.677034,8718.916797,70039.901401,4.552800,637.557700,0.185100
std,2.293890e+06,1.743846,1421.399078,6627.164762,20072.214143,1.566862,60.657906,0.388398
min,1.000324e+06,0.000000,46.783973,31.652732,1000.000000,0.000000,408.000000,0.000000
25%,2.977661e+06,0.000000,3154.235371,4199.836020,56539.867903,3.000000,597.000000,0.000000
50%,4.989502e+06,1.000000,4052.377228,6732.407217,70085.826330,5.000000,638.000000,0.000000
75%,6.967210e+06,2.000000,5052.898103,11272.263740,83429.166133,6.000000,679.000000,0.000000
max,8.999789e+06,5.000000,10750.677810,43688.784100,148412.180500,10.000000,850.000000,1.000000

Analyser la qualité des données

In [8]:
# Valeurs manquantes
df.isnull().sum()
df.isnull().mean() * 100  # en %

customer_id                 0.0
credit_lines_outstanding    0.0
loan_amt_outstanding        0.0
total_debt_outstanding      0.0
income                      0.0
years_employed              0.0
fico_score                  0.0
default                     0.0
dtype: float64

In [9]:
# Doublons
df.duplicated().sum()

np.int64(0)

In [10]:
# Valeurs aberrantes (outliers)
df.describe(percentiles=[.01, .05, .25, .75, .95, .99])

,customer_id,credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score,default
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.974577e+06,1.461200,4159.677034,8718.916797,70039.901401,4.552800,637.557700,0.185100
std,2.293890e+06,1.743846,1421.399078,6627.164762,20072.214143,1.566862,60.657906,0.388398
min,1.000324e+06,0.000000,46.783973,31.652732,1000.000000,0.000000,408.000000,0.000000
1%,1.079081e+06,0.000000,1230.977265,583.845780,22676.764735,1.000000,490.990000,0.000000
5%,1.415055e+06,0.000000,2044.005453,1236.690508,37001.349620,2.000000,536.000000,0.000000
25%,2.977661e+06,0.000000,3154.235371,4199.836020,56539.867903,3.000000,597.000000,0.000000
50%,4.989502e+06,1.000000,4052.377228,6732.407217,70085.826330,5.000000,638.000000,0.000000
75%,6.967210e+06,2.000000,5052.898103,11272.263740,83429.166133,6.000000,679.000000,0.000000
95%,8.583714e+06,5.000000,6646.026569,22900.195794,102825.766100,7.000000,735.000000,1.000000
99%,8.911466e+06,5.000000,7923.321782,29708.836295,117258.351239,8.000000,778.010000,1.000000
max,8.999789e+06,5.000000,10750.677810,43688.784100,148412.180500,10.000000,850.000000,1.000000

Analyser les distributions

In [11]:
import matplotlib.pyplot as plt
import seaborn as sns

df[""].hist(bins=30)
df["categorie"].value_counts().plot(kind="bar")

KeyboardInterrupt: